### ISSUE TITLE
Python 3.10 compatibility?

### ISSUE THREAD

**Issue by intelfx** [libfuse/pyfuse3#51]
pyfuse 3.2.1 fails to build on python 3.10

```
$ cd pyfuse3-release-3.2.1 

$ python setup.py build_cython       
found MANIFEST.in, running in developer mode
running build_cython
Compiling /mnt/ssd/Scratch/makepkg/python-pyfuse3/src/pyfuse3-release-3.2.1/src/pyfuse3.pyx

$ python setup.py build_ext --inplace
found MANIFEST.in, running in developer mode
running build_ext
building 'pyfuse3' extension
creating build
creating build/temp.linux-x86_64-3.10
creating build/temp.linux-x86_64-3.10/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/include/python3.10 -c src/pyfuse3.c -o build/temp.linux-x86_64-3.10/src/pyfuse3.o -I/usr/include/fuse3 -DFUSE_USE_VERSION=32 -Wall -Wextra -Wconversion -Wsign-compare -DPYFUSE3_VERSION="3.2.1" -Wno-unused-function -Wno-implicit-fallthrough -Wno-unused-function -Wno-unused-parameter -Werror -Wfatal-errors -Wno-error=unreachable-code -Werror=conversion -Werror=sign-compare
src/pyfuse3.c:53221:1: error: missing initializer for field 'am_send' of 'PyAsyncMethods' [-Werror=missing-field-initializers]
53221 | };
      | ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
error: command '/usr/bin/gcc' failed with exit code 1
```

I can see that the error is in generated code, but I've really no idea what to do with it. Python 3.10.0, Cython 0.29.25. Doesn't happen with python 3.9.9.

**Comment by Nikratio** [comment]
This is probably a bug in Cython, which doesn't/didn't yet support Python 3.10. Could you please try this again with most recent Cython?
